### PR TITLE
Added Buildscript and .gitignore

### PR DESCRIPTION
**Pull request by HerXayah**

### CODE REVIEW

**Comment by Hexality** [comment]
I'm using PowerShell PAckager by IronManSoftware instead of PS2EXE btw, hence why I uploaded the Package.psd1 xD

**Comment by Hexality** [comment]
doing that cause IMS Packager is less likely to be accused with a false-positive (differently from ps2exe which is knon for getting flagged all the time)

**Comment by Hexality** [comment]
btw, did you confirm that ps2exe built exe works? cause iIrc, ps2exe doesn't support PS7 and netcore, which is required for this script due to some weird winform flags.

**Comment by HerXayah** [comment]
> btw, did you confirm that ps2exe built exe works? cause iIrc, ps2exe doesn't support PS7 and netcore, which is required for this script due to some weird winform flags.

It works.
Its just for building the EXE bc importing Stuff in ps7 is eh.

**Comment by Hexality** [comment]
ok, thx for the commit

**Pull request merged**
